### ISSUE TITLE
Crash in large size remote video

### ISSUE THREAD

**Issue by kfung0426** [googlesamples/cardboard-ios#1]
Hi, the app crash when I call a remote video(about 100MB):

[_videoView loadFromUrl:[NSURL URLWithString:http://cdn2b.download.sample.phncdn.com/videos/201603/18/71401761/vl_1080P_1971.0k_71401761.mp4?rs=50000&ri=50000&ipa=203.186.100.100&s=1459409665&e=1459416865&h=1b52b1217db0a790bc1d79e155697a0e]];

The debug console shows:
Message from debugger: Terminated due to memory issue

**Comment by hitnology** [comment]
can't open your url
I have tried to add an MONO 360 video to the demo, the memory usage increase fast and soon termated.

**Comment by kfung0426** [comment]
Yes, the url just an example.
I have tried to upload congo.mp4 to web server, it works.
But when I try a large mp4 file, the app terminated within 5 seconds. Anyone can help?

**Comment by hitnology** [comment]
@kfung0426 my problem is Stereo 360 videos are ok,but Mono 360 videos will terminted soon

**Comment by congsun** [comment]
@kfung0426 Got the same problem :( Any progress?

**Comment by nathanmartz** [comment]
Thank you for the bug report. We're looking into this now.

**Comment by herrernst** [comment]
Mono Videos (2:1, e.g. 1024x512 or 1920x960) are also not working for me, even if they are local and very small (1MB). Nothing happens, app just stops after ~5 secs. In device console, I get:
```
Apr  1 12:51:46 iPhone6 SpringBoard[58] <Warning>: BSXPCMessage received error for message: Connection invalid
Apr  1 12:51:46 iPhone6 SpringBoard[58] <Warning>: BSXPCMessage received error for message: Connection invalid
Apr  1 12:51:46 iPhone6 SpringBoard[58] <Warning>: HW kbd: Failed to set (null) as keyboard focus
Apr  1 12:51:47 iPhone6 UserEventAgent[26] <Notice>: jetsam: kernel termination snapshot being created
Apr  1 12:51:47 iPhone6 com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.124
	[520] <Warning>: 1 +0.000000 sec [0208/1307]: error: ::read ( -1, 0x16e246a38, 1024 ) => -1 err = Bad file descriptor (0x00000009)
Apr  1 12:51:47 iPhone6 com.apple.debugserver-@(#)PROGRAM:debugserver  PROJECT:debugserver-340.3.124
	[520] <Warning>: Exiting.
Apr  1 12:51:47 iPhone6 gputoolsd[511] <Notice>: schedule invalidation <DYTransport 0x127eab890, error: explicit invalidation (6)>
Apr  1 12:51:47 iPhone6 gputoolsd[511] <Notice>: schedule invalidation <DYTransport 0x127e0f5a0, error: lost transport connection (31)>
Apr  1 12:51:47 iPhone6 gputoolsd[511] <Notice>: terminating daemon 0x127e0f260
Apr  1 12:51:47 iPhone6 ReportCrash[523] <Warning>: Report of type '298(298)' not saved because the limit of 25 logs has been reached
Apr  1 12:51:47 iPhone6 SpringBoard[58] <Warning>: Application 'UIKitApplication:com.google.VideoWidgetDemo[0xd409]' was killed by jetsam.
Apr  1 12:51:47 iPhone6 UserEventAgent[26] <Warning>: 570997550237: id=com.google.VideoWidgetDemo pid=521, state=0
Apr  1 12:51:47 iPhone6 searchd[131] <Warning>: ====^^^^ DuetExpert missing data, count -> people:0 applicationDeepLinks:0 applications:8 requests:19 missingAllDataRequests:0
```

**Comment by nathanmartz** [comment]
We can repro and have a fix here. We're doing QA on an update and will hopefully have more to share shortly.

**Comment by justin-distaulo** [comment]
I am having this issue as well. When attempting to load large videos the app will sometimes crash (about 25% of attempts initially). The problem seems to get worse over time eventually reducing successful loads to near 0%.

**Comment by nathanmartz** [comment]
We've just posted an updated cocopod that fixes this issue.

**Comment by herrernst** [comment]
Thanks, works now.
