### ISSUE TITLE
GCSVideoView setting ?

### ISSUE THREAD

**Issue by liamscofield** [googlesamples/cardboard-ios#10]
I wrote a demo as demo what demo did , but I get the result of video up-down side,just like be split to two pieces. 
<img width="366" alt="2016-04-13 4 01 36" src="https://cloud.githubusercontent.com/assets/4811145/14486729/17e7aedc-0191-11e6-9c70-ef96d1b620e1.png">

**Comment by malliodiao** [comment]
it should be the same problem of issue #7 , this behaviour appeared after update to pod 0.7.1

**Comment by liamscofield** [comment]
Yep, 0.7.1 is the first time I ever use in my project, @malliodiao you're right I will close the issue
