### ISSUE TITLE
Fail to switch to another video in one GCSVideoView

### ISSUE THREAD

**Issue by wsdfz** [googlesamples/cardboard-ios#11]
If one video is loaded (in either playing or stopped mode), try load another video will crash APP.
[_videoView loadFromUrl:[[NSURL alloc] initFileURLWithPath:videoPath];

It will throw EXC_BAD_ACCESS at com.google.cardboard.RenderThread (9):
#0	0x00000001001ebedc in ion::gfx::Renderer::GetInternalResourceBinder(unsigned long*) const ()

...
    0x1001ebed0 <+60>:  bl     0x1001ff20c               ; std::__1::__hash_iterator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, std::__1::shared_ptr<ion::gfx::Renderer::ResourceBinder> >, void*>*> std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, std::__1::shared_ptr<ion::gfx::Renderer::ResourceBinder> >, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, std::__1::shared_ptr<ion::gfx::Renderer::ResourceBinder> >, std::__1::hash<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, std::__1::shared_ptr<ion::gfx::Renderer::ResourceBinder> >, std::__1::equal_to<unsigned long>, true>, ion::base::StlAllocator<std::__1::__hash_value_type<unsigned long, std::__1::shared_ptr<ion::gfx::Renderer::ResourceBinder> > > >::find<unsigned long>(unsigned long const&)
    0x1001ebed4 <+64>:  cbz    x0, 0x1001ebee8           ; <+84>
    0x1001ebed8 <+68>:  ldr    x20, [x0, #24]
->  0x1001ebedc <+72>:  ldr    x8, [x19, #56]
...

Is there a way to switch to another video smoothly? If use another GCSVideoView, it will show the initialization screen again.

**Comment by sanjayc77** [comment]
Fixed in 0.7.2

**Comment by Tynug** [comment]
Hello,

I have nearly the same issue but with SDK 0.9
