### ISSUE TITLE
Pod Install Failure

### ISSUE THREAD

**Issue by allenwong** [googlesamples/cardboard-ios#2]
First of all, I changed the pod file and append a target, actually I am testing the Panorama project, and import the missing "GCSPanoramaView.h" file.

```
target 'Panorama' do
pod 'CardboardSDK', '~> 0.7.0'
end
```

Then I get a sad result

```
[!] Error installing CardboardSDK
!] /usr/bin/curl -f -L -o /var/folders/nd/hbb3rk3n0516qf_7_9d3mqmc0000gn/T/d20160331-5157-ce7nme/file.tgz https://www.gstatic.com/cpdc/97ceadc125bddf66-CardboardSDK-0.7.0.tar.gz --create-dirs
...
Failed to connect to www.gstatic.com port 443: Operation timed out
```

**Comment by hitnology** [comment]
from china?
change a vpn

**Comment by allenwong** [comment]
I turn on VPN 24 hours, It's failed even under the VPN network.

**Comment by hitnology** [comment]
@allenwong I changed many vpn services until I fetch the code.just try another vpn

**Comment by nathanmartz** [comment]
Sounds like a Great Firewall issue.

**Comment by change2hao** [comment]
@hitnology I encountered the same issue,could you tell me which vpn works well?

**Comment by gityoung** [comment]
@change2hao   No one can use only download SDK. https://www.gstatic.com/cpdc/4d33147568331bb6-CardboardSDK-0.7.2.tar.gz
