### ISSUE TITLE
-> Installing CardboardSDK (0.7.2)  time out

### ISSUE THREAD

**Issue by gityoung** [googlesamples/cardboard-ios#21]
can not  pod  success 

[!] Error installing CardboardSDK
[!] /usr/bin/curl -f -L -o /var/folders/s9/sss1yz7j76v9br278lz56k5m0000gn/T/d20160516-16103-cbqz4x/file.tgz https://www.gstatic.com/cpdc/4d33147568331bb6-CardboardSDK-0.7.2.tar.gz --create-dirs --netrc

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0curl: (7) Failed to connect to www.gstatic.com port 443: Operation timed out

**Comment by MingleChang** [comment]
try VPN
