### ISSUE TITLE
- widgetView:didLoadContent: not called

### ISSUE THREAD

**Issue by malliodiao** [googlesamples/cardboard-ios#6]
widgetView:didLoadContent: never gets called after a GCSVideoView or GCSPanoramaView are loaded successfully, and delegates are correct

**Comment by sanjayc77** [comment]
- widgetView:didLoadContent worked for GCSPanoramaView for me. I had to add the GCSWidgetViewDelegate implementation to the PanoramaViewController and set it as a delegate on the panoView.

It did not work for GCSVideoView. But a workaround is to use - videoView:didUpdatePosition delegate method. It gets called when the video is ready to play, which means it was successfully loaded.

**Comment by sanjayc77** [comment]
Fixed in 0.7.2
